### ISSUE TITLE
Дизайн задания "Соотнеси начало и конец идиом"

### ISSUE THREAD

**Issue by id-andyyy** [id-andyyy/Fruit-idioms#4]
Придумать дизайн для задания "Connect the beginning and the end of the idioms". Дизайн должен учитывать:
- место первой части каждой идиомы
- место второй части каждой идиомы
- разный размер частей идиом (идиомы могут быть короткие, а могут быть длинные)
- поля для ввода цифры
- место для показа ответа
- формат показанного ответа
- адаптацию для просмотра на телефоне

Желательно использовать встроенную в Bootstrap адаптацию (использование row и col).

**Comment by strawberry2892** [comment]
https://www.figma.com/file/3b77UXLtSAcQ2JnbS5NBUt/2-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5?type=design&node-id=0%3A1&mode=design&t=nDygghaNcC6F6AmC-1
